name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
  
  
jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install
        run: |
          npm ci
          npm ls

      - name: Build
        run: |
          npm run build-storybook
          
      - name: "Retain build artifact: Storybook"
        uses: actions/upload-artifact@v2
        with:
          name: storybook
          path: storybook-static
          retention-days: 1

  publish-storybook:
    runs-on: ubuntu-latest
    needs: continuous-integration
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: "Restore build artifact: Storybook"
        uses: actions/download-artifact@v2
        with:
          name: storybook
          path: storybook-static

      - name: Continuous Deployment to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: storybook-static
